version: 0.1
phases:
  install:
    commands:
      - curl -L "https://github.com/docker/compose/releases/download/1.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
  build:
    commands:
      - echo "Build started"
      - chmod +x ./bin/build
      - chmod +x ./bin/_build
      - ./bin/build
artifacts:
  files:
    - build/hhttpserver
