FROM debian:8.7

ENV LANG C.UTF-8
ENV LANGUAGE C.UTF-8
ENV LC_ALL C.UTF-8

RUN apt-get update

RUN apt-get install -y ghc \
  && apt-get install -y cabal-install

RUN apt-get install -y zlib1g-dev

RUN cabal update

RUN cabal install hspec
RUN cabal install webdriver
RUN cabal install hspec-webdriver

WORKDIR /code/
