version: "2"
services:
  hhttpserver_build:
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - .:/code
  hhttpserver_run:
    build:
      context: .
      dockerfile: Dockerfile.run
    volumes:
      - .:/code
    ports:
      - 8080:80
