FROM debian:8.7

ENV LANG C.UTF-8
ENV LANGUAGE C.UTF-8
ENV LC_ALL C.UTF-8

RUN apt-get update

RUN apt-get install -y ghc=7.6.3-21 \
  && apt-get install -y cabal-install=1.20.0.3-1

RUN cabal update
RUN cabal install network-2.6.3.1 \
  && cabal install containers-0.5.10.1 \
  && cabal install split-0.2.3.1

WORKDIR /code/
