FROM debian:8.7

ENV LANG C.UTF-8
ENV LANGUAGE C.UTF-8
ENV LC_ALL C.UTF-8

# Slightly horribly these are not statically linked
RUN apt-get update
RUN apt-get install -y libgmp10=2:6.0.0+dfsg-6 libffi6=3.1-2+b2  

WORKDIR /code/

CMD ./build/hhttpserver
