FROM debian:8.7

ENV LANG C.UTF-8
ENV LANGUAGE C.UTF-8
ENV LC_ALL C.UTF-8

RUN apt-get update

RUN apt-get install -y ghc \
  && apt-get install -y cabal-install

RUN cabal update

RUN cabal install hspec

WORKDIR /code/
