version: "2"

services:

  hhttpserver_build:
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - .:/code

  hhttpserver_run:
    build:
      context: .
      dockerfile: Dockerfile.run
    volumes:
      - .:/code
    ports:
      - 8080:80

  hhttpserver_run_for_test:
    build:
      context: .
      dockerfile: Dockerfile.run
    volumes:
      - .:/code
    expose:
      - "80"

  hhttpserver_test:
    build:
      context: .
      dockerfile: Dockerfile.test
    links:
      - selenium
    volumes:
      - .:/code

  selenium:
    image: selenium/standalone-chrome:2.53.1
    links:
      - hhttpserver_run_for_test
    expose:
     - "4444"
